[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python ./src/run_schedule_assistant/main.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3