[build]
builder = "NIXPACKS"

[deploy]
startCommand = "uvicorn src.run_schedule_assistant.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3